production:
  adapter: postgresql
  encoding: unicode
  database: ENV["DATABASE"]
  username: ENV["USER"]
  password: ENV["PASSWORD"]

development:
  adapter: postgresql
  encoding: unicode
  database: glean_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: glean_test
  pool: 5
  host: localhost
